### ISSUE TITLE
\textsuperscript{} in `publication` leads to error

### ISSUE THREAD

**Issue by koppor** [adbrucker/authorarchive#23] opened 2022-07-11 21:55 UTC
```tex
\documentclass{article}
\usepackage[IEEE,
   publication={The 6\textsuperscript{th} conference},
   nobib
 ]{authorarchive}
\begin{document}
Test
\end{document}
```

Output (both with lualatex and pdflatex)

```
LaTeX2e <2022-06-01> patch level 3
 L3 programming layer <2022-06-16> (C:/MiKTeX/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:/MiKTeX/tex/latex/base/size10.clo)))
! Incomplete \iffalse; all text was ignored after line 6.
<inserted text>
\fi
<*> test.tex

?
! Emergency stop.
<inserted text>
\fi
<*> test.tex
```

**Comment by adbrucker** [comment] 2022-07-15 11:09
Thanks a lot for reporting this issue. I will need to have a closer look. The problem is caused by the use of `\DeclareStringOptions` from the package `kvoption`, i.e., the following minimal example already triggers this problem:
```tex
\documentclass{article}
\begin{filecontents}{aa-test.sty}
  \RequirePackage{kvoptions}
  \DeclareStringOption[UNKNOWN PUBLICATION]{publication}[]
  \ProcessKeyvalOptions*
\end{filecontents}
\usepackage[publication={The 6\textsuperscript{th} conference}]{aa-test}
\begin{document}
Test
\end{document}
```
Further investigations are  needed to decide, if this counts as a bug in `kvoptions` or if this is a wrong use of `\DeclareStringOption` (is a LaTeX command, strictly speaking, a string).

**Comment by adbrucker** [comment] 2022-07-16 19:33
Hi,
this is a fundamental problem caused by the way how LaTeX passes options to packages and classes (see also <https://tex.stackexchange.com/questions/489564/use-unexpanded-macro-in-package-options>, which also mentions that this is the reason the package `hyperref` provides the command `\hypersetup{}`). 

The package `authorarchive` already provides the command `\authorsetup{}`, which can be used for setting the publication information, i.e., the following should work with the latest released version of `authorarchive`:

```tex
\documentclass{article}
\usepackage[IEEE,
   nobib
 ]{authorarchive}
\authorsetup{
   publication={The 6\textsuperscript{th} conference}
}
\begin{document}
Test
\end{document}
```

Note that, due to a bug in the current implementation of `authorinfo` the `key` parameter *must* be passed as package option. I will later commit an update that fixes this issue and also change the documentation and examples to solely use `\authorsetup{}`. After that, I will close this bug report.

**Closed as completed** 2022-07-16 20:50 UTC
